イベント開催会場を「株式会社インプレス」に更新
ababy115/ichiyasaGitSample pull request #1
Opened 2023-05-28 15:25 UTC by ababy115

### 変更内容
イベント会場を「株式会社インプレス」に更新しました。

### 背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2023-05-28 15:46 UTC, taku115 commented
修正ありがとうございます！問題ないのでマージします。

2023-06-02 14:04 UTC, taku115 reviewed
I have just one queation to you. @ababy115

2023-06-02 14:30 UTC, ababy115 commented on index.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorig
Yeah, I thought the same thing! but my boss said so.

2023-06-02 14:44 UTC, taku115 approved these changes
I think it's good to marge.

2023-06-02 14:44 UTC, taku115 commented on index.html
> +    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" cros
LGTM!

2023-06-02 14:59 UTC, taku115 requested changes
test 🧪

2023-06-02 15:23 UTC, merged